version: '3'
services:  
  docker-nginx:
    container_name: docker-nginx
    image: nginx:alpine
    restart: always
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
    - app
  docker-mysql:
    container_name: docker-mysql
    image: mysql/mysql-server
    command: --default-authentication-plugin=mysql_native_password --innodb_buffer_pool_size=1024M --innodb_read_io_threads=4 --innodb_flush_log_at_trx_commit=2 --innodb_flush_method=O_DIRECT
    environment:
      MYSQL_DATABASE: traffic_accident_expertise_calculation_tool
      MYSQL_ROOT_PASSWORD: Nalim050979
      MYSQL_ROOT_HOST: '%'
    ports:
    - 3306:3306
    volumes:
    - dbdata:/var/lib/mysql
    restart: always
  app:
    image: milan79/traffic-accident-analysis-calculation-tool:latest
    working_dir: /app
    restart: always
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    expose:
    - '8080'
    depends_on:
    - docker-mysql 
volumes:
  dbdata: 